// ============================================
// WORD DATABASE - Words with difficulty-based points
// ============================================

export interface WordEntry {
  text: string;
  points: number;
}

// Points based on difficulty:
// Easy (5-8 pts): Common words
// Medium (10-15 pts): Moderately difficult
// Hard (18-25 pts): Uncommon or complex words

export const WORD_DATABASE: WordEntry[] = [
  // Easy words (5-8 points)
  { text: "elephant", points: 6 },
  { text: "pizza", points: 5 },
  { text: "guitar", points: 6 },
  { text: "rainbow", points: 5 },
  { text: "banana", points: 5 },
  { text: "hospital", points: 6 },
  { text: "birthday", points: 5 },
  { text: "football", points: 5 },
  { text: "ice cream", points: 5 },
  { text: "umbrella", points: 6 },
  { text: "butterfly", points: 6 },
  { text: "telephone", points: 5 },
  { text: "helicopter", points: 7 },
  { text: "strawberry", points: 6 },
  { text: "sunglasses", points: 6 },
  { text: "chocolate", points: 5 },
  { text: "basketball", points: 5 },
  { text: "watermelon", points: 6 },
  { text: "christmas", points: 5 },
  { text: "sandwich", points: 5 },
  { text: "fireworks", points: 6 },
  { text: "dinosaur", points: 6 },
  { text: "keyboard", points: 6 },
  { text: "popcorn", points: 5 },
  { text: "pineapple", points: 6 },
  
  // Easy Celebrities (5-8 points) - Well-known, easy to guess
  { text: "Taylor Swift", points: 5 },
  { text: "Beyonce", points: 5 },
  { text: "Drake", points: 5 },
  { text: "Rihanna", points: 5 },
  { text: "Eminem", points: 5 },
  { text: "Shakira", points: 5 },
  { text: "Adele", points: 5 },
  { text: "Madonna", points: 5 },
  { text: "Justin Bieber", points: 5 },
  { text: "Ed Sheeran", points: 6 },
  { text: "Michael Jackson", points: 5 },
  { text: "Elvis Presley", points: 6 },
  { text: "Tom Cruise", points: 5 },
  { text: "Brad Pitt", points: 5 },
  { text: "Angelina Jolie", points: 6 },
  { text: "Leonardo DiCaprio", points: 7 },
  { text: "Will Smith", points: 5 },
  { text: "Johnny Depp", points: 5 },
  { text: "Tom Hanks", points: 5 },
  { text: "Oprah Winfrey", points: 6 },
  { text: "Ellen DeGeneres", points: 7 },
  { text: "Kim Kardashian", points: 6 },
  { text: "Cristiano Ronaldo", points: 7 },
  { text: "Lionel Messi", points: 6 },
  { text: "LeBron James", points: 6 },
  { text: "Serena Williams", points: 7 },
  { text: "Elon Musk", points: 5 },
  { text: "Bill Gates", points: 5 },
  { text: "Jeff Bezos", points: 6 },
  { text: "Mark Zuckerberg", points: 7 },
  
  // Medium words (10-15 points)
  { text: "escalator", points: 12 },
  { text: "astronaut", points: 10 },
  { text: "gymnastics", points: 12 },
  { text: "avalanche", points: 14 },
  { text: "earthquake", points: 10 },
  { text: "submarine", points: 10 },
  { text: "parachute", points: 11 },
  { text: "quicksand", points: 13 },
  { text: "xylophone", points: 14 },
  { text: "binoculars", points: 12 },
  { text: "compass", points: 10 },
  { text: "hibernate", points: 13 },
  { text: "origami", points: 12 },
  { text: "symphony", points: 14 },
  { text: "eclipse", points: 12 },
  { text: "volcano", points: 10 },
  { text: "penguin", points: 8 },
  { text: "glacier", points: 12 },
  { text: "pyramid", points: 10 },
  { text: "tornado", points: 10 },
  { text: "microscope", points: 11 },
  { text: "lighthouse", points: 10 },
  { text: "chameleon", points: 13 },
  { text: "jellyfish", points: 10 },
  { text: "kaleidoscope", points: 15 },
  
  // NEW Medium words - Batch 1: Nature & Weather (10-15 points)
  { text: "hurricane", points: 10 },
  { text: "blizzard", points: 11 },
  { text: "monsoon", points: 12 },
  { text: "aurora", points: 12 },
  { text: "tundra", points: 11 },
  { text: "savanna", points: 11 },
  { text: "meadow", points: 10 },
  { text: "canyon", points: 10 },
  { text: "waterfall", points: 10 },
  { text: "archipelago", points: 14 },
  
  // NEW Medium words - Batch 2: Occupations (10-15 points)
  { text: "architect", points: 11 },
  { text: "librarian", points: 10 },
  { text: "pharmacist", points: 12 },
  { text: "journalist", points: 11 },
  { text: "detective", points: 10 },
  { text: "electrician", points: 12 },
  { text: "veterinarian", points: 13 },
  { text: "blacksmith", points: 12 },
  { text: "carpenter", points: 10 },
  { text: "locksmith", points: 12 },
  
  // NEW Medium words - Batch 3: Animals (10-15 points)
  { text: "kangaroo", points: 10 },
  { text: "crocodile", points: 10 },
  { text: "flamingo", points: 11 },
  { text: "scorpion", points: 11 },
  { text: "pelican", points: 10 },
  { text: "mongoose", points: 12 },
  { text: "anteater", points: 11 },
  { text: "hedgehog", points: 10 },
  { text: "manatee", points: 12 },
  { text: "meerkat", points: 11 },
  
  // NEW Medium words - Batch 4: Food & Cooking (10-15 points)
  { text: "avocado", points: 10 },
  { text: "lasagna", points: 11 },
  { text: "spaghetti", points: 10 },
  { text: "pancake", points: 10 },
  { text: "cinnamon", points: 11 },
  { text: "pistachio", points: 12 },
  { text: "artichoke", points: 12 },
  { text: "asparagus", points: 11 },
  { text: "zucchini", points: 12 },
  { text: "jalapeño", points: 13 },
  
  // NEW Medium words - Batch 5: Music & Instruments (10-15 points)
  { text: "harmonica", points: 11 },
  { text: "accordion", points: 12 },
  { text: "saxophone", points: 11 },
  { text: "tambourine", points: 12 },
  { text: "clarinet", points: 11 },
  { text: "trombone", points: 11 },
  { text: "mandolin", points: 12 },
  { text: "ukulele", points: 12 },
  { text: "marimba", points: 13 },
  { text: "bagpipes", points: 12 },
  
  // NEW Medium words - Batch 6: Sports & Activities (10-15 points)
  { text: "snorkeling", points: 11 },
  { text: "kayaking", points: 11 },
  { text: "wrestling", points: 10 },
  { text: "fencing", points: 11 },
  { text: "toboggan", points: 12 },
  { text: "javelin", points: 12 },
  { text: "discus", points: 12 },
  { text: "polo", points: 10 },
  { text: "squash", points: 11 },
  { text: "curling", points: 11 },
  
  // NEW Medium words - Batch 7: Household Items (10-15 points)
  { text: "chandelier", points: 13 },
  { text: "fireplace", points: 10 },
  { text: "wardrobe", points: 10 },
  { text: "bookshelf", points: 10 },
  { text: "aquarium", points: 11 },
  { text: "thermometer", points: 12 },
  { text: "blender", points: 10 },
  { text: "toaster", points: 10 },
  { text: "dishwasher", points: 10 },
  { text: "mattress", points: 11 },
  
  // NEW Medium words - Batch 8: Transportation (10-15 points)
  { text: "sailboat", points: 10 },
  { text: "scooter", points: 10 },
  { text: "trolley", points: 11 },
  { text: "gondola", points: 12 },
  { text: "catamaran", points: 13 },
  { text: "rickshaw", points: 13 },
  { text: "zeppelin", points: 14 },
  { text: "hovercraft", points: 12 },
  { text: "monorail", points: 12 },
  { text: "caboose", points: 12 },
  
  // NEW Medium words - Batch 9: Clothing & Accessories (10-15 points)
  { text: "cardigan", points: 11 },
  { text: "suspenders", points: 11 },
  { text: "bandana", points: 10 },
  { text: "poncho", points: 11 },
  { text: "kimono", points: 12 },
  { text: "sombrero", points: 11 },
  { text: "turban", points: 11 },
  { text: "moccasins", points: 12 },
  { text: "corduroy", points: 12 },
  { text: "cashmere", points: 13 },
  
  // Hard words (18-25 points)
  { text: "czechoslovakia", points: 22 },
  { text: "onomatopoeia", points: 25 },
  { text: "supercalifragilistic", points: 25 },
  { text: "pneumonia", points: 20 },
  { text: "archaeological", points: 22 },
  { text: "entrepreneur", points: 20 },
  { text: "metamorphosis", points: 20 },
  { text: "photosynthesis", points: 18 },
  { text: "ventriloquist", points: 22 },
  { text: "hieroglyphics", points: 23 },
  { text: "schizophrenia", points: 24 },
  { text: "worcestershire", points: 25 },
  { text: "antidisestablishmentarianism", points: 25 },
  { text: "otorhinolaryngologist", points: 25 },
  { text: "serendipity", points: 18 },
  { text: "surveillance", points: 18 },
  { text: "conscientious", points: 20 },
  { text: "bureaucracy", points: 18 },
  { text: "phenomenon", points: 18 },
  { text: "quarantine", points: 15 },
  { text: "camouflage", points: 15 },
  { text: "labyrinth", points: 18 },
  { text: "silhouette", points: 18 },
  { text: "millennium", points: 18 },
  { text: "catastrophe", points: 16 },
  
  // NEW Hard words - Batch 1: Scientific & Medical Terms (18-25 points)
  { text: "anesthesiologist", points: 24 },
  { text: "bioluminescence", points: 22 },
  { text: "cardiovascular", points: 20 },
  { text: "deoxyribonucleic", points: 25 },
  { text: "electromagnetic", points: 20 },
  { text: "gastroenterology", points: 24 },
  { text: "hypothermia", points: 18 },
  { text: "immunodeficiency", points: 23 },
  { text: "neuroplasticity", points: 22 },
  { text: "ophthalmologist", points: 24 },
  { text: "pathophysiology", points: 24 },
  { text: "psychoanalysis", points: 20 },
  { text: "radioactivity", points: 18 },
  { text: "stethoscope", points: 18 },
  { text: "thermodynamics", points: 20 },
  { text: "ultrasonography", points: 22 },
  { text: "vertebrae", points: 18 },
  { text: "xeroderma", points: 22 },
  { text: "zygote", points: 18 },
  { text: "pharmacology", points: 20 },
  
  // NEW Hard words - Batch 2: Philosophy & Literature (18-25 points)
  { text: "existentialism", points: 20 },
  { text: "transcendentalism", points: 24 },
  { text: "epistemology", points: 22 },
  { text: "nihilism", points: 18 },
  { text: "solipsism", points: 20 },
  { text: "pseudonymous", points: 20 },
  { text: "bibliophile", points: 18 },
  { text: "oneiromancy", points: 22 },
  { text: "perspicacious", points: 22 },
  { text: "sesquipedalian", points: 24 },
  
  // NEW Hard words - Batch 3: Unusual English Words (18-25 points)
  { text: "acquiesce", points: 18 },
  { text: "bourgeoisie", points: 22 },
  { text: "cacophony", points: 18 },
  { text: "discombobulate", points: 20 },
  { text: "ephemeral", points: 18 },
  { text: "flabbergasted", points: 18 },
  { text: "gobbledygook", points: 20 },
  { text: "hullabaloo", points: 18 },
  { text: "idiosyncratic", points: 20 },
  { text: "juxtaposition", points: 20 },
  { text: "kerfuffle", points: 18 },
  { text: "loquacious", points: 18 },
  { text: "mischievous", points: 18 },
  { text: "nonchalant", points: 18 },
  { text: "obsequious", points: 20 },
  { text: "pernicious", points: 18 },
  { text: "quintessential", points: 20 },
  { text: "rendezvous", points: 18 },
  { text: "surreptitious", points: 22 },
  { text: "tintinnabulation", points: 25 },
  
  // NEW Hard words - Batch 4: Foreign Loanwords (18-25 points)
  { text: "doppelganger", points: 18 },
  { text: "schadenfreude", points: 22 },
  { text: "zeitgeist", points: 20 },
  { text: "wanderlust", points: 18 },
  { text: "kindergarten", points: 16 },
  { text: "angst", points: 16 },
  { text: "karaoke", points: 16 },
  { text: "tsunami", points: 16 },
  { text: "entrepreneur", points: 20 },
  { text: "bourgeois", points: 20 },
  
  // NEW Hard words - Batch 5: Architecture & Art (18-25 points)
  { text: "chiaroscuro", points: 22 },
  { text: "trompeloeil", points: 24 },
  { text: "renaissance", points: 18 },
  { text: "baroque", points: 18 },
  { text: "amphitheater", points: 18 },
  { text: "mausoleum", points: 18 },
  { text: "colosseum", points: 18 },
  { text: "parquetry", points: 20 },
  { text: "terracotta", points: 18 },
  { text: "portico", points: 18 },
  

  // NEW Hard words - Batch 9: Mythology & Religion (18-25 points)
  { text: "prometheus", points: 18 },
  { text: "persephone", points: 18 },
  { text: "mjolnir", points: 22 },
  { text: "ragnarok", points: 20 },
  { text: "mesopotamia", points: 18 },
  { text: "zoroastrianism", points: 24 },
  { text: "reincarnation", points: 18 },
  { text: "transubstantiation", points: 25 },
  { text: "excommunication", points: 22 },
  { text: "eschatology", points: 22 },
  
  // NEW Hard words - Batch 10: Miscellaneous Challenging (18-25 points)
  { text: "onychophagia", points: 24 },
  { text: "defenestration", points: 22 },
  { text: "verisimilitude", points: 22 },
  { text: "circumlocution", points: 20 },
  { text: "pusillanimous", points: 22 },
  { text: "magnanimous", points: 18 },
  { text: "fastidious", points: 18 },
  { text: "perfunctory", points: 18 },
  { text: "obstreperous", points: 20 },
  { text: "perspicacity", points: 22 },
  
  // Country & Place names
  { text: "switzerland", points: 15 },
  { text: "madagascar", points: 14 },
  { text: "liechtenstein", points: 22 },
  { text: "kyrgyzstan", points: 24 },
  { text: "azerbaijan", points: 22 },
  { text: "mozambique", points: 18 },
  { text: "kazakhstan", points: 20 },
  { text: "uzbekistan", points: 20 },
  { text: "tajikistan", points: 22 },
  { text: "turkmenistan", points: 22 },
  
  // Food & Cuisine
  { text: "guacamole", points: 12 },
  { text: "cappuccino", points: 14 },
  { text: "croissant", points: 14 },
  { text: "bruschetta", points: 16 },
  { text: "ratatouille", points: 18 },
  { text: "prosciutto", points: 18 },
  { text: "tiramisu", points: 14 },
  { text: "chimichanga", points: 16 },
  { text: "quesadilla", points: 14 },
  { text: "fettuccine", points: 16 },
  
  // Animals
  { text: "hippopotamus", points: 14 },
  { text: "chimpanzee", points: 12 },
  { text: "orangutan", points: 14 },
  { text: "platypus", points: 12 },
  { text: "armadillo", points: 12 },
  { text: "chinchilla", points: 14 },
  { text: "salamander", points: 12 },
  { text: "porcupine", points: 10 },
  { text: "tarantula", points: 12 },
  { text: "rhinoceros", points: 14 },
  
  // Technology & Science
  { text: "algorithm", points: 14 },
  { text: "bluetooth", points: 10 },
  { text: "cryptocurrency", points: 16 },
  { text: "hologram", points: 12 },
  { text: "bandwidth", points: 14 },
  { text: "megapixel", points: 14 },
  { text: "encryption", points: 16 },
  { text: "nanotechnology", points: 18 },
  { text: "quantum", points: 14 },
  { text: "satellite", points: 10 },
  
  // Sports & Games
  { text: "badminton", points: 10 },
  { text: "trampoline", points: 10 },
  { text: "boomerang", points: 12 },
  { text: "skateboard", points: 8 },
  { text: "volleyball", points: 8 },
  { text: "surfboard", points: 10 },
  { text: "archery", points: 10 },
  { text: "marathon", points: 10 },
  { text: "bobsled", points: 14 },
  { text: "lacrosse", points: 14 },
  
  // Misc challenging words
  { text: "adrenaline", points: 14 },
  { text: "archaeology", points: 16 },
  { text: "bankruptcy", points: 14 },
  { text: "cemetery", points: 12 },
  { text: "democracy", points: 12 },
  { text: "eloquent", points: 16 },
  { text: "fascinate", points: 12 },
  { text: "gorgeous", points: 10 },
  { text: "hypnotize", points: 14 },
  { text: "ignorance", points: 12 },
  { text: "jealousy", points: 12 },
  { text: "knowledge", points: 10 },
  { text: "melancholy", points: 16 },
  { text: "nostalgia", points: 14 },
  { text: "oblivious", points: 14 },
  { text: "parallel", points: 12 },
  { text: "questionnaire", points: 18 },
  { text: "rhapsody", points: 16 },
  { text: "spectacular", points: 12 },
  { text: "tremendous", points: 12 },
];

// Shuffle array using Fisher-Yates algorithm
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

// Get shuffled word pool for a game
export function getShuffledWordPool(): WordEntry[] {
  return shuffleArray(WORD_DATABASE);
}
